version: '3.3'

services:
  bible_db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./config/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bible-db:/var/lib/mysql

volumes:
  bible-db: