version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./config/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: