version: '3.3'

services:
  app:
    container_name: full_app
    build: .
    env_file:
      - ./config/.env
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - bible_db
    networks:
      - fullstack

  bible_db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./config/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bible-db:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  bible-db:

networks:
  fullstack:
    driver: bridge